### ISSUE TITLE
langの読み込みに失敗します。

### ISSUE THREAD

**Issue by haniokasai** [hmy2001/PermissionPlus#2]
タイトルのまんまです。
"Failed to read the language file..."
になります。

**Comment by hmy2001** [comment]
設定ファイルでのlangはどうでしょうか？
バージョンも載せてくれると嬉しいです

**Comment by hmy2001** [comment]
@haniokasai

**Comment by haniokasai** [comment]
すみません　原因わかりました。
バージョンは現在のものです。
githubのdownload　zip のところからダウンロードして、解凍すると、PermissionPlus-masterにフォルダの名前がなります。そのままpluginsに投入するとエラーになるようです。
お騒がせしました。

**Comment by hmy2001** [comment]
なおって良かったです
