### ISSUE TITLE
0.16.0にてコマンドのパーミッション設定が適応されません

### ISSUE THREAD

**Issue by Kuri0421** [hmy2001/PermissionPlus#3]
src側の問題かもしれませんが listをop以外でも使えるように設定してましたが0.16.0から全く使えなくなってしまいました

**Comment by hmy2001** [comment]
問題解決のため、利用しているsrcを教えて下さい

**Comment by Kuri0421** [comment]
Genisysの派生版ですがElywingを使用してます
[https://github.com/H4PM/Elywing](url)

**Comment by hmy2001** [comment]
プレイヤーにopを与えると正常になる可能性がありますが、確認します。

**Comment by hmy2001** [comment]
ただ今確認したところ正常に動作しました。(Genisys)

**Comment by hmy2001** [comment]
設定が適応されない前に何か操作を行いましたか？

**Comment by Kuri0421** [comment]
私もGenisysでは動作確認ができました
