### ISSUE TITLE
1.6.0 1.6.1を入れると落ちる　1.6.0 1.6.1 drops and falls

### ISSUE THREAD

**Issue by effect320** [hmy2001/PermissionPlus#7]
1.6.0 1.6.1をプラグインフォルダに入れてpmmpを起動すると、
[PermissionPlus] Failed to load lang file.
と赤文字で表示されて落ちてしまいます。直してください。

Start pmmp by putting 1.6.0 1.6.1 into the plug-in folder.
[Permission Plus] Failed to load lang file.
It will be displayed in red letters and will fall. please fix this.

**Comment by hmy2001** [comment]
Fixed it.
修正しました
